# Generated by Django 4.0.6 on 2025-11-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
